Feature/mobile menu
Shahid-Bagwan/Portfolio pull request #11
Opened 2023-06-26 22:34 UTC by Shahid-Bagwan

- add mobile menu.
- add style for the menu.
- change the height o background images

2023-06-26 22:43 UTC, Efiamotu-1 reviewed
Hi @Shahid-Bagwan , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif) 

You have submitted a project, that doesn't have all linters setup. currently you do not have linters to check your javascript code visit this [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js) to properly setup linters and resubmit :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-27 03:02 UTC, zieeco requested changes
Hi @Afsheen96,


<img height="180" src="https://media1.giphy.com/media/5jOttxlszbgaAHeHOg/giphy.gif"/>

Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Mobile menu is almost done.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions


- N/A
 
**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 03:02 UTC, zieeco commented on index.js
> +  navToggle.addEventListener('click', () => toggle());
- Hey, according to the requirement, if a user clicks on any of the menu items, it should take the user to that specific part of the webpage. However, this has not been implemented. please, let's fix this.
- Also, on clicking the different links, the menu should disappear. please, fix this also.

2023-06-27 04:50 UTC, Afsheen96 commented
Which repository is this???

On Tue, 27 Jun 2023, 8:02 am zieeco, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Afsheen96 <https://github.com/Afsheen96>,
>
>
> <https://camo.githubusercontent.com/7d83e5cb16187c036cee27af7dbec8f9c430a7de6525b4a0f4ed93db4554ca84/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f356a4f7474786c737a626761414865484f672f67697068792e676966>
>
> Great job so far! 👏
> You've done well, however, there are some issues that you still need to
> work on to go to the next project, but you are almost there!
> To highlight 🎯
>
>    - Mobile menu is almost done.✔️
>    - Nice design. ✔️
>    - Descriptive PR. ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
>    - N/A
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers, and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Remember to tag me in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think the code review was unfair, you can request a
> second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.js
> <https://github.com/Shahid-Bagwan/Portfolio/pull/11#discussion_r1243081954>
> :
>
> > +document.addEventListener('DOMContentLoaded', () => {
> +  const navToggle = document.getElementsByTagName('button')[0];
> +  const title = document.getElementsByTagName('h1')[0];
> +  const links = document.getElementsByTagName('ul')[0];
> +  const main = document.getElementsByTagName('main')[0];
> +  const footer = document.getElementsByTagName('footer')[0];
> +  const nav = document.getElementsByTagName('nav')[0];
> +  const i = document.querySelector('#close_menu');
> +  function toggle() {
> +    links.classList.toggle('show_nav');
> +    main.classList.toggle('test');
> +    footer.classList.toggle('test');
> +    title.classList.toggle('test');
> +    nav.classList.toggle('navbar');
> +    nav.classList.toggle('navbar1');
> +    i.classList.toggle('fas');
> +    i.classList.toggle('fa-bars');
> +    i.classList.toggle('fa-xs');
> +    i.classList.toggle('fa-solid');
> +    i.classList.toggle('fa-xmark');
> +  }
> +  navToggle.addEventListener('click', () => toggle());
>
>
>    - Hey, according to the requirement, if a user clicks on any of the
>    menu items, it should take the user to that specific part of the webpage.
>    However, this has not been implemented. please, let's fix this.
>    - Also, on clicking the different links, the menu should disappear.
>    please, fix this also.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Shahid-Bagwan/Portfolio/pull/11#pullrequestreview-1499858506>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5HVNFA2BNIYBVDQ46MEIF3XNJENHANCNFSM6AAAAAAZUYYPF4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-27 06:47 UTC, Afsheen96 commented on index.js
> +  navToggle.addEventListener('click', () => toggle());
Sorry sir i am confused as i am not the collaborator of this reop this is not my project so why did you mention me 🤔🤔🤔 @zieeco

2023-06-27 21:42 UTC, Shahid-Bagwan commented on index.js
> +  navToggle.addEventListener('click', () => toggle());
done
!

2023-06-27 21:48 UTC, usorfaitheloho approved these changes
Hi @Shahid-Bagwan  👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 23:09 UTC, merged